// Generated by CoffeeScript 1.7.1
(function() {
  var Cylon, config, robot;

  Cylon = require("cylon");

  config = {
    connection: {
      name: "arduino",
      adaptor: "firmata",
      port: "/dev/tty.usbmodem1a12151"
    },
    device: {
      name: "led",
      driver: "led",
      pin: 13
    }
  };

  config.work = function(my) {
    return my.arduino.analogRead(0, function(voltage) {
      console.log('voltage', voltage);
      return my.led.brightness();
    });
  };

  robot = Cylon.robot(config);

  robot.start();

}).call(this);
