// Generated by CoffeeScript 1.7.1
(function() {
  var Cylon, config, robot;

  Cylon = require("cylon");

  config = {
    connection: {
      name: "arduino",
      adaptor: "firmata",
      port: "/dev/tty.usbmodem1a12151"
    },
    device: {
      name: "led",
      driver: "led",
      pin: 13
    }
  };

  config.work = function(my) {
    var currentVoltage;
    currentVoltage = 0;
    return my.arduino.analogRead(0, function(voltage) {
      var delay;
      if (voltage === currentVoltage) {
        return;
      }
      currentVoltage = voltage;
      delay = voltage / 1000;
      my.led.turnOn();
      return after(delay.seconds(), function() {
        return my.led.turnOff();
      });
    });
  };

  robot = Cylon.robot(config);

  robot.start();

}).call(this);
